server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: yb-pictrue-backend
  session:
    store-type: redis
    #30天过期
    timeout: 2592000
  servlet:
    multipart:
      max-file-size: 10MB
  # Redis 配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password: 123456
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yb_picture
    username: root
    password: 1234

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yb.cloudPictrueBackend.controller
# 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucket: